[metadata]
creation_date = "2023/04/03"
min_stack_version = "8.5.0"
maturity = "production"
updated_date = "2023/04/03"

[rule]
name = "[Custom] Create persistance: Modify Screensaver"
author = ["Andrey Krasnov"]
description = """
This rule will generate an alert when the SCRNSAVE.exe key is changed (added) by Sysmon 13 or WinEventLog 4657.
"""
from = "now-5m"
index = ["winlogbeat-*", "logs-system.*", "logs-windows.*"]
language = "eql"
license = ""
note = """

"""
references = [
    "https://attack.mitre.org/techniques/T1546/002/",
]
risk_score = 47
rule_id = "5b4b27f6-a9ed-4783-a1ea-432a1a3be72e"
severity = "medium"
tags = ["Windows", "Threat Detection", "Persistence", "TA0003", "Event Triggered Execution", "T1546", "Screensaver", "T1546.002", "SCRNSAVE.exe", "Registry"]
type = "eql"

query = '''
registry where (
	/*	WinEventLog	4657 + SACL for key	*/
	event.provider: "Microsoft-Windows-Security-Auditing" and event.code: "4657" and winlog.event_data.ObjectName like~ "*Control Panel\\Desktop*" and winlog.event_data.ObjectValueName like~ "SCRNSAVE.exe" and winlog.event_data.NewValue not in~ ("", "-")
	)
	or (
	/*	Sysmon 13 + XML	*/
	event.provider: "Microsoft-Windows-Sysmon" and event.code: "13" and registry.path like~ "*Control Panel\\Desktop*" and registry.value like~ "SCRNSAVE.exe" and  registry.data.strings not in~ ("", "-")
	)
'''


[[rule.threat]]
framework = "MITRE ATT&CK"

[[rule.threat.technique]]
id = "T1546"
name = "Event Triggered Execution"
reference = "https://attack.mitre.org/techniques/T1546/"

[[rule.threat.technique.subtechnique]]
id = "T1546.002"
name = "Screensaver "
reference = "https://attack.mitre.org/techniques/T1546/002/"

[rule.threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"