[metadata]
creation_date = "2023/04/20"
min_stack_version = "8.5.0"
maturity = "production"
updated_date = "2023/04/20"

[rule]
name = "CUSTOM: Create persistence: Hidden Registry Run Keys (based on registry activity)"
author = ["Andrey Krasnov"]
description = """
This rule will generate an alert when the *//Run* key is changed (added) by Sysmon 13 or WinEvt 4657 or WinEvt 4663.
Accesses for 4663: 0x1 - ReadData 0x2 - WriteData
"""
from = "now-5m"
index = ["winlogbeat-*", "logs-system.*", "logs-windows.*"]
language = "eql"
license = ""
note = """

"""
references = [
    "https://attack.mitre.org/techniques/T1547/001/",
	"https://github.com/elastic/detection-rules/blob/main/rules/windows/persistence_run_key_and_startup_broad.toml",
	"https://github.com/elastic/detection-rules/blob/main/rules/windows/persistence_via_hidden_run_key_valuename.toml",
	"https://github.com/outflanknl/SharpHide",
	"https://github.com/ewhitehats/InvisiblePersistence"
]
risk_score = 47
rule_id = "faee5e4a-e2c1-42ac-8cad-ba2e87bd43a4"
severity = "medium"
tags = ["Windows", "Threat Detection", "Persistence", "TA0003", "Boot or Logon Autostart Execution", "T1547", "Registry Run Keys / Startup Folder", "T1547.001"]
type = "eql"

query = '''
any where (
	/*	Sysmon 13	*/
	event.code: "13"
	and registry.path like~ "*\\currentversion\\*run*" and registry.value like~ "Run*"
	and registry.data.strings not in~ ("", "-")
	)
	or (
	/*	WinEventLog	4657 + SACL for key	*/
	event.code: "4657"
	and winlog.event_data.ObjectName like~ "*\\currentversion\\*run*"
	and ?winlog.event_data.ObjectValueName == null
	and ?winlog.event_data.OldValue == null
	and winlog.event_data.NewValue: "%%1904" 
	)
'''


[[rule.threat]]
framework = "MITRE ATT&CK"

[[rule.threat.technique]]
id = "T1547"
name = "Boot or Logon Autostart Execution"
reference = "https://attack.mitre.org/techniques/T1547/"

[[rule.threat.technique.subtechnique]]
id = "T1547.001"
name = "Registry Run Keys / Startup Folder"
reference = "https://attack.mitre.org/techniques/T1547/001/"

[rule.threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"