[metadata]
creation_date = "2023/04/03"
min_stack_version = "8.5.0"
maturity = "production"
updated_date = "2023/04/03"

[rule]
name = "[Custom] Create persistence: Shortcut Modification "
author = ["Andrey Krasnov"]
description = """
This rule will generate an alert when the access to LNK file was obtained with:
AccessMask 0x2 - WriteData or 0x6 - WriteData | AppendData by WinEventLog 4663
"""
from = "now-5m"
index = ["winlogbeat-*", "logs-system.*", "logs-windows.*"]
language = "eql"
license = ""
note = """

"""
references = [
    "https://attack.mitre.org/techniques/T1547/009/"
]
risk_score = 47
rule_id = "be5922e4-14c5-4aa2-861d-5bd7a9e4cbd4"
severity = "medium"
tags = ["Windows", "Threat Detection", "Persistence", "TA0003", "Boot or Logon Autostart Execution", "T1547", "Shortcut Modification", "T1547.009", "Shortcut", "LNK", "Modify"]
type = "eql"

query = '''
any where {
	/*	WinEventLog 4663*/
	event.provider: "Microsoft-Windows-Security-Auditing"  and event.code: "4663" and winlog.event_data.ObjectType: "File" and  winlog.event_data.AccessMask in ("0x6", "0x2") and winlog.event_data.ObjectName like~ "*.lnk"
	)
'''

[[rule.threat]]
framework = "MITRE ATT&CK"

[[rule.threat.technique]]
id = "T1547"
name = "Boot or Logon Autostart Execution"
reference = "https://attack.mitre.org/techniques/T1547/"

[[rule.threat.technique.subtechnique]]
id = "T1547.009"
name = "Shortcut Modification "
reference = "https://attack.mitre.org/techniques/T1547/009/"

[rule.threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"