[metadata]
creation_date = "2023/04/03"
min_stack_version = "8.5.0"
maturity = "production"
updated_date = "2023/04/03"

[rule]
name = "[Custom] Use persistence: Start process from StartupFolder"
author = ["Andrey Krasnov"]
description = """
This rule will generate an alert when a process started from *Startup directory by WinEventLog 4663 (read file by exeplorer.exe), WinEventLog 4688, Sysmon 11. Accesses: 0x1 - ReadData
"""
from = "now-5m"
index = ["winlogbeat-*", "logs-system.*", "logs-windows.*"]
language = "eql"
license = ""
note = """

"""
references = [
    "https://attack.mitre.org/techniques/T1547/001/"
]
risk_score = 47
rule_id = "6f5b6ccd-75a1-4b49-ba3b-5527840d4b91"
severity = "medium"
tags = ["Windows", "Threat Detection", "Persistence", "TA0003", "Boot or Logon Autostart Execution", "T1547", "Registry Run Keys / Startup Folder", "T1547.001", "Start Process", "Startup Folder"]
type = "eql"

query = '''
any where (
	/*	[+/-] WinEventLog 4663, read file by explorer	*/
	event.provider: "Microsoft-Windows-Security-Auditing" and event.code: "4663" and winlog.event_data.ObjectType: "File" and winlog.event_data.ObjectName like~ "*\\startup\\*" and winlog.event_data.AccessMask: "0x1" and winlog.event_data.ProcessName like~ "*\\explorer.exe"
	)
	or (
	/*	Sysmon 11	*/
	event.provider: "Microsoft-Windows-Sysmon" and event.code: "1" and process.name != "" and process.parent.name like~ "*explorer.exe*" and process.executable like~ "*\\startup\\*"
	)
	or (
	/*	WinEventLog 4688	*/
	event.provider: "Microsoft-Windows-Security-Auditing" and event.code: "4688" and process.name != "" and process.parent.name like~ "*explorer.exe*" and process.executable like~ "*\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\*"
	)
'''

[[rule.threat]]
framework = "MITRE ATT&CK"

[[rule.threat.technique]]
id = "T1547"
name = "Boot or Logon Autostart Execution"
reference = "https://attack.mitre.org/techniques/T1547/"

[[rule.threat.technique.subtechnique]]
id = "T1547.001"
name = "Registry Run Keys / Startup Folder"
reference = "https://attack.mitre.org/techniques/T1547/001/"

[rule.threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"