[metadata]
creation_date = "2023/04/03"
min_stack_version = "8.5.0"
maturity = "production"
updated_date = "2023/04/20"

[rule]
name = "CUSTOM: Use persistence: Start process as RunOnce"
author = ["Andrey Krasnov"]
description = """
This rule will generate an alert when the process will starts in follow sequence: runonce.exe -> TargetProcess with WinEventLog 4688 or Sysmon 1 audit.
"""
from = "now-5m"
index = ["winlogbeat-*", "logs-system.*", "logs-windows.*"]
language = "eql"
license = ""
note = """

"""
references = [
    "https://attack.mitre.org/techniques/T1547/001/",
	"https://github.com/elastic/detection-rules/blob/main/rules/windows/persistence_run_key_and_startup_broad.toml",
	"https://github.com/elastic/detection-rules/blob/main/rules/windows/persistence_via_hidden_run_key_valuename.toml",
	"https://github.com/outflanknl/SharpHide",
	"https://github.com/ewhitehats/InvisiblePersistence"
]
risk_score = 47
rule_id = "608375e4-9612-49b9-81d5-588c4115841b"
severity = "medium"
tags = ["Windows", "Threat Detection", "Persistence", "TA0003", "Boot or Logon Autostart Execution", "T1547", "Registry Run Keys / Startup Folder", "T1547.001", "RunOnce", "Start Process", "runonce.exe"]
type = "eql"

query = '''
sequence by host.name with maxspan=30s
	[process where process.command_line like~"runonce.exe*/Explorer"]
	until [process where process.parent.name like~ "runonce.exe" and not process.command_line like~ "iernonce.dll*RunOnceExProcess"]
	
	
(
	[process where process.command_line like~"runonce.exe*/Explorer"]
	[process where process.parent.name like~ "runonce.exe" and not process.command_line like~ "iernonce.dll*RunOnceExProcess"]
	)
	or (
	[process where process.command_line like~"runonce.exe*/Explorer"]
	[process where process.parent.name like~ "runonce.exe" and process.command_line like~"runonce.exe*/RunOnce6432"]
	[process where process.parent.name like~ "runonce.exe" and not process.command_line like~ "iernonce.dll*RunOnceExProcess"]
	)
'''

[[rule.threat]]
framework = "MITRE ATT&CK"

[[rule.threat.technique]]
id = "T1547"
name = "Boot or Logon Autostart Execution"
reference = "https://attack.mitre.org/techniques/T1547/"

[[rule.threat.technique.subtechnique]]
id = "T1547.001"
name = "Registry Run Keys / Startup Folder"
reference = "https://attack.mitre.org/techniques/T1547/001/"

[rule.threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"